ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS period           TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS before_connection TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS after_connection  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS usage_feel        TEXT NOT NULL DEFAULT '';
